language: python
python:
  - 3.5
  - 3.6
dist: xenial
sudo: required
services:
  - xvfb
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install gfortran
  - git clone https://github.com/Axelrod-Python/TourExec.git /tmp/TourExec
  - cd /tmp/TourExec
  - sudo make install
  - echo "/usr/lib/libstrategies.so" | sudo tee /etc/ld.so.conf.d/strategies-lib.conf
  - sudo ldconfig
  - ldconfig -p | grep libstrategies.so
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install -r requirements.txt
  - pip install pytest
script:
    - pytest
